process.env.VITE_SUPABASE_URL ??= 'https://wzjjqllpgqpvqxbjbndk.supabase.co';
process.env.VITE_SUPABASE_ANON_KEY ??= 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6ampxbGxwZ3FwdnF4YmpibmRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1OTU1MTEsImV4cCI6MjA3ODE3MTUxMX0.6nFQq1vPd6UK9_eak_RIf7m3pipPB_oGtfrPu1RTtq8';
